#!/usr/bin/env python3
#!/usr/bin/env python3
# script: vlookup.py
# contact: siva.selvanayagam@wur.nl
# description: vlookup between two files
# input: Input file, Lookup file
# output: Output file
# version: 1.0
# date: 16-05-2023
import sys

import pandas as pd
from collections import defaultdict
import argparse

parser = argparse.ArgumentParser(description='print the lines from the input file for the entries from lookup file for a specific column')
parser.add_argument('-i', '--input', help='Input file', required=True)
parser.add_argument('-l', '--lookup', help='Lookup file', required=True)
parser.add_argument('-o', '--output', help='Output file', required=True)
parser.add_argument('-c', '--column', type=int, help='Column to lookup (in the Input file)', required=True)
args = parser.parse_args()


def get_dict_lookup(lookup_file, column):
    """
    Convert a lookup dataframe to a dictionary
    Parameters
    ----------
    lookup_df
    key
    value

    Returns
    -------
    lookup_dict : dict
    """
    lookup_list = []
    with open(lookup_file, 'r') as f:
        for line in f:
            line = line.strip().split('\t')
            if line[column] in lookup_list:
                print('Duplicate key in the lookup file: ' + line[column])
                sys.exit(1)
            lookup_list.append(line[column])
    return lookup_list


lookup_list = get_dict_lookup(args.lookup, args.column)
out_fo = open(args.output, "w")
with open(args.input, 'r') as f:
    for line in f:
        line = line.strip()
        data = line.split('\t')
        if data[args.column] in lookup_list:
            out_fo.write(f"{line}\n")

