#!/bin/bash

# this will set the script to exit if any statement returns a non-true return value
set -e
## this will print each command before executing it
#set -x
# this will set the script to exit if any pipeline returns a non-true return value
set -o pipefail

# Get the directory of the script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Default heap size 24GB
DEFAULT_HEAP_SIZE="24G"

# Use custom heap size if provided, otherwise use default
HEAP_SIZE=${MEGANOME_HEAP_SIZE:-$DEFAULT_HEAP_SIZE}

# Default tmp directory
DEFAULT_TMP_DIR="/tmp"

# Use custom tmp directory if provided, otherwise use default
TMP_DIR=${MEGANOME_TMP_DIR:-$DEFAULT_TMP_DIR}

# Set Java options
JAVA_OPTS=(-Xms256M -Xmx"$HEAP_SIZE" -Djava.io.tmpdir="$TMP_DIR")

# if local host ends with .bioinformatics.nl then run the below command
if [[ $(hostname --fqdn) == *.bioinformatics.nl ]]; then
    JAR_FILE="/lustre/BIF/nobackup/selva001/work/jars/meganome-0.0.1-SNAPSHOT.jar"
else
    JAR_FILE="/Users/selva001/projects/meganome/src/meganome/target/meganome-0.0.1-SNAPSHOT.jar"
fi

# Run the JAR file with Java options and any provided arguments
exec java "${JAVA_OPTS[@]}" -jar "$JAR_FILE" "$@"
