#!/usr/bin/env python3

import argparse
import os

def main():
    parser = argparse.ArgumentParser(description='filter the psl file (from blat output) to remove the alignments '
                                                 'with low identity and coverage')
    parser.add_argument('-i', '--input', help='input psl file', required=True)
    parser.add_argument('-o', '--output', help='output psl file', required=True)
    parser.add_argument('-q', '--q_cov', help='query coverage threshold', required=True, type=float, default=0.8)
    parser.add_argument('-d', '--idty', help='identity threshold', required=True, type=float, default=0.8)
    parser.add_argument('-b', '--nblocks', help='maximum number of blocks threshold', required=True, type=int, default=100)
    args = parser.parse_args()

    with open(args.input, 'r') as f, open(args.output, 'w') as g:
        # check if the file has header
        for line in f:
            line = line.strip().split('\t')
            if len(line) < 21:
                g.write('\t'.join(line) + '\n')
                continue
            aln_len = sum([int(i) for i in line[18].split(',')[:-1]])
            q_cov = aln_len / int(line[10])
            idty = int(line[0]) / int(line[10])
            if q_cov <= args.q_cov:
                continue
            if idty <= args.idty:
                continue
            if int(line[17]) > args.nblocks:
                continue
            g.write('\t'.join(line) + '\n')


if __name__ == "__main__":
    main()